### ISSUE TITLE
Node.js 12 GitHub Actions are deprecated

### ISSUE THREAD

**Issue by dgschwindturo** [KeisukeYamashita/setup-release#282]
Seeing this warning at Lint time : `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: KeisukeYamashita/setup-release@v1.0.2`

**Comment by KeisukeYamashita** [comment]
Sorry for the late reply, I will update it soon!

**Comment by KeisukeYamashita** [comment]
Thank you! https://github.com/KeisukeYamashita/setup-release/pull/283
